### ISSUE TITLE
Iterating the event buffer does not scale well

### ISSUE THREAD

**Issue by Corniel** [Qowaiv/qowaiv-domainmodel#33]
If compared to iterating an array, a list, and the event buffer (created by adding one item at the time), it becomes clear that iterating does not scale. Somewhere between 10k and 100k it even breaks by throwing a stack-overflow exception. The implementation should be reconsidered.

|       Method |  Count |        Mean | Ratio |
|------------- |-------:|------------:|------:|
|        array |   1,000 |    10.65 us |  1.00 |
|         list |   1,000 |    14.10 us |  1.32 |
| event buffer |   1,000 |    36.38 us |  3.42 |
|              |        |             |       |
|        array |  10,000 |   100.37 us |  1.00 |
|         list |  10,000 |   136.01 us |  1.36 |
|  event buffer|  10,000 |   507.69 us |  5.06 |
|              |        |             |       |
|        array | 100,000 | 1,063.29 us |  1.00 |
|         list | 100,000 | 1,442.91 us |  1.36 |
| event buffer | 100,000 |          NA |     ? |

**Comment by CptWesley** [comment]
I think this can be closed now.
